[package]
name = "unfair_advantage"
version = "0.1.0"
authors = ["sanisoclem <me@jerahmeelcosinas.net>"]
edition = "2021"

[dependencies]
bevy = "0.6"
bevy_egui = "0.11.1"
bevy_rapier2d = { version = "0.12.1", features = [ "simd-stable" ] }
bevy_ecs_tilemap ="0.5"

[profile.dev.package."*"]
opt-level = 3
