[package]
name = "unfair_advantage"
version = "0.1.0"
authors = ["sanisoclem <me@jerahmeelcosinas.net>"]
edition = "2021"

[dependencies]
bevy = "0.6"
bevy_egui = "0.11.1"
heron = { version = "2.0.1", features = ["2d", "debug-2d"] }
# heron = { version = "2.0.1", features = ["2d"] }
bevy_ecs_tilemap = { git = "https://github.com/StarArawn/bevy_ecs_tilemap", rev = "8a5f1c764afd04f828b56784ba086484aa34da6d" }
rand = "0.8"
bevy-inspector-egui = "0.8.2"
bevy_editor_pls = { git = "https://github.com/jakobhellermann/bevy_editor_pls", branch = "main" }
bevy_prototype_lyon = "0.4.0"
sha2 = "0.10.2"

[profile.dev.package."*"]
opt-level = 3
