[package]
name = "unfair_advantage"
version = "0.1.0"
authors = ["sanisoclem <me@jerahmeelcosinas.net>"]
edition = "2021"

[dependencies]
bevy = "0.6"
bevy_egui = "0.11.1"

[profile.dev.package."*"]
opt-level = 3
